version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ThankMrGoose
      MYSQL_DATABASE: coop_mmr
    volumes:
      - ./sql_scripts/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./sql_scripts/populate_tables_docker.sql:/docker-entrypoint-initdb.d/02_populate_tables.sql
      - ./sql_scripts/sample_data:/docker-entrypoint-initdb.d/sample_data
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ThankMrGoose
      DB_DATABASE: coop_mmr
    ports:
      - 5000:5000
    volumes:
      - ./server/src/:/app/src/

  web:
    build:
      context: ./web
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./web/public/:/app/public/
      - ./web/src/:/app/src/
