LOAD DATA LOCAL INFILE 'sample_data/student.txt' INTO TABLE STUDENT COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/company.txt' INTO TABLE COMPANY COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/tag.txt' INTO TABLE TAG COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/job.txt' INTO TABLE JOB COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/placement.txt' INTO TABLE PLACEMENT COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/review.txt' INTO TABLE REVIEW COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'sample_data/job_tag.txt' INTO TABLE JOB_TAG COLUMNS TERMINATED BY '\t';