LOAD DATA LOCAL INFILE 'data/student.tsv' INTO TABLE STUDENT COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'data/company.tsv' INTO TABLE COMPANY COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'data/job.tsv' INTO TABLE JOB COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'data/placement.tsv' INTO TABLE PLACEMENT COLUMNS TERMINATED BY '\t';
LOAD DATA LOCAL INFILE 'data/review.tsv' INTO TABLE REVIEW COLUMNS TERMINATED BY '\t';
-- LOAD DATA LOCAL INFILE 'data/tag.tsv' INTO TABLE TAG COLUMNS TERMINATED BY '\t';
-- LOAD DATA LOCAL INFILE 'data/job_tag.tsv' INTO TABLE JOB_TAG COLUMNS TERMINATED BY '\t';
